Repository fraction/oasis, pull requests merged in 2020-02, with the labels that each got.

#122 Make 'Popular' page faster
  src/models/index.js
Labels: enhancement

#145 Make "key not found" error more useful
  src/models.js
Labels: bug

#143 Fix /image/ URL returning a broken image
  src/http.js
  src/index.js
Labels: bug

#133 Make 'Following' page way faster
  src/models.js
Labels: enhancement

#162 Fix socialFilter() to change `{ me = null }`
  src/models.js
Labels: bug

#168 Fix emoji and breaking space in main nav
  src/assets/style.css
  src/views/index.js
Labels: bug

#169 Remove nosniff from blob URLs
  src/http.js
Labels: bug

#174 Re-add publish to nav menu
  src/views/index.js
Labels: bug

#154 Add invite code
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#181 Add --public option for public viewers
  src/cli.js
  src/index.js
  src/models.js
Labels: enhancement

#188 Fix bug where others could still change your name
  src/models.js
Labels: bug

#196 Replace cooler methods with SSB-Client promises
  package-lock.json
  package.json
  src/models.js
  src/ssb.js
Labels: enhancement

#198 Improve readme with more details about Oasis
  README.md
Labels: enhancement

#200 Fix sources bug and thread ancestor bug
  src/models.js
Labels: bug

#210 Use color emoji in Markdown posts
  src/views/markdown.js
Labels: cosmetic, enhancement

#206 Fix popular page to only show posts from following
  src/models.js
Labels: bug

#212 Fix publish not working without content warning
  src/index.js
Labels: bug

#214 Hide custom publish behind publish menu
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#219 Show a preview of comments in listings
  .gitignore
  src/assets/style.css
  src/models.js
  src/views/index.js
Labels: enhancement

#218 Fix likes not working with Patchwork as server
  .cspell.json
  src/ssb.js
Labels: bug

#225 Redirect search to SSB references
  src/index.js
Labels: enhancement

#229 Remove references to npm registry publish
  .github/workflows/npmpublish.yml
  README.md
Labels: enhancement

#228 Add AUTHORS and MAINTAINERS files
  docs/AUTHORS
  docs/MAINTAINERS
Labels: enhancement

#223 Create 'Summaries' page for new summary view
  src/assets/style.css
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#232 Add Oasis version to settings
  package-lock.json
  package.json
  src/index.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#233 Redirect to Latest after publishing new message
  src/index.js
Labels: enhancement

#235 Add friendly EADDRINUSE error message
  src/index.js
Labels: enhancement

#236 Remove private messages from Mentions
  src/models.js
Labels: bug

#234 Remove image border
  src/assets/style.css
  src/index.js
Labels: bug

#230 Replace messagesByType() with SSB-Query read
  src/models.js
Labels: bug

#244 Remove private posts from public views
  src/models.js
Labels: bug

#246 Update SSB-Mentions and remove workaround
  package-lock.json
  package.json
  src/index.js
Labels: enhancement

#248 Add docs/translating.md -- instructions for adding new languages
  docs/translating.md
Labels: documentation

#247 Add Termux install documentation
  .cspell.json
  docs/install.md
  docs/with-termux.md
Labels: documentation

#269 Add hashtag support to search
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: bug, enhancement, patchwork parity

#263 Hide search results from blocked feeds
  src/models.js
Labels: bug, safety

#262 Detect existing Oasis server running on interface
  src/index.js
Labels: enhancement

#260 Fix queries with an unused `{index: "DTA"}` option
  src/models.js
Labels: bug

#261 Add profile edit page
  src/assets/style.css
  src/index.js
  src/models.js
  src/views/index.js
Labels: enhancement

#271 Show channel as text appended to posts
  src/models.js
Labels: enhancement

#270 Fix Extended page sorting posts incorrectly
  src/models.js
Labels: bug
