Repository fraction/oasis, pull requests merged in 2020-03, with the labels that each got.

#298 Upgrade npm dependencies
  package-lock.json
  package.json
Labels: enhancement, patchwork parity

#299 Present error message while waiting for indexing
  .cspell.json
  src/http.js
  src/index.js
Labels: bug, patchwork parity

#277 Add profile image upload
  .cspell.json
  src/index.js
  src/models.js
  src/views/index.js
Labels: enhancement

#325 Indexing error message
  src/index.js
  src/views/index.js
Labels: enhancement

#251 Add build script that creates zip files
  scripts/build.sh
  scripts/oasis.go
Labels: enhancement

#335 Fix crash when linking directly to private message
  src/models.js
Labels: bug

#340 Update npm dependencies
  .eslintrc.js
  .travis.yml
  package-lock.json
  package.json
  src/cli.js
  src/http.js
  src/index.js
  src/models.js
  src/ssb.js
  src/views/i18n.js
  src/views/index.js
  src/views/markdown.js
Labels: enhancement

#348 Text-based browser spacing issues and sticky headers enhancement
  src/assets/style.css
  src/views/i18n.js
  src/views/index.js
Labels: cosmetic, enhancement

#349 Fix theme using capitalization
  .cspell.json
  src/cli.js
Labels: bug, cosmetic

#353 Introduces Threads
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#345 Remove version question from issue template
  .github/ISSUE_TEMPLATE.md
Labels: process

#342 Only show connected peers in settings
  src/views/index.js
Labels: bug

#356 Fix Markdown link bug
  package-lock.json
  package.json
Labels: bug

#365 Add Matrix chat room to readme
  README.md
Labels: documentation, process

#341 Don't append channel to non-root posts
  src/models.js
Labels: bug

#368 Add contributing and maintainting documents
  docs/contract.md
  docs/contributing.md
  docs/maintaining.md
Labels: documentation, process

#366 Avoid processing popular posts twice
  src/models.js
Labels: bug

#339 Automatically connect to replicated peers
  src/ssb.js
Labels: enhancement, networking

#363 Add TypeScript definitions for better guardrails
  package-lock.json
  package.json
  src/cli.js
  src/http.js
  src/index.js
  src/ssb.js
  src/views/i18n.js
  src/views/index.js
  src/views/markdown.js
Labels: enhancement

#372 Add block and unblock to author profile
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#379 Fix z-index on sticky header
  src/assets/style.css
Labels: cosmetic

#378 Updates query for threads
  src/models.js
Labels: bug
