Repository fraction/oasis, pull requests merged in 2020-01, with the labels that each got.

#31 Add support for running oasis in a docker container
  .dockerignore
  Dockerfile
  README.md
  src/pages/models/lib/cooler.js
  src/pages/models/lib/server.js
Labels: topic:enhancement

#39 Change systemd unit to use `default.target`
  contrib/oasis.service
Labels: topic:bug

#37 Add install-systemd-service.js
  .cspell.json
  contrib/install-systemd-service.bash
  contrib/install-systemd-service.js
  docs/with-systemd.md
  package.json
Labels: topic:enhancement

#41 Add automatic reconnection on failure
  src/pages/models/lib/cooler.js
Labels: topic:bug

#43 Add CLI flag for offline mode (using temporary hack with globals)
  index.js
  src/pages/models/lib/server.js
Labels: topic:enhancement

#45 Change issue template to be less annoying
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: help wanted, topic:enhancement

#46 Use mediator pattern to simplify architecture
  docs/contributing.md
  index.js
  package.json
  src/app.js
  src/cli.js
  src/http.js
  src/index.js
  src/models/index.js
  src/models/markdown.js
  src/pages/author.js
  src/pages/blob.js
  src/pages/comment.js
  src/pages/compose.js
  src/pages/hashtag.js
  src/pages/image.js
  src/pages/inbox.js
  src/pages/json.js
  src/pages/like.js
  src/pages/likes.js
  src/pages/markdown.js
  src/pages/mentions.js
  src/pages/meta.js
  src/pages/models/about.js
  src/pages/models/blob.js
  src/pages/models/friend.js
  src/pages/models/lib/configure.js
  src/pages/models/lib/cooler.js
  src/pages/models/lib/server.js
  src/pages/models/meta.js
  src/pages/models/post.js
  src/pages/models/vote.js
  src/pages/profile.js
  src/pages/public-latest.js
  src/pages/public-popular.js
  src/pages/publish-comment.js
  src/pages/publish-reply.js
  src/pages/publish.js
  src/pages/reply.js
  src/pages/search.js
  src/pages/thread.js
  src/pages/views/author.js
  src/pages/views/comment.js
  src/pages/views/list.js
  src/pages/views/markdown.js
  src/pages/views/meta.js
  src/pages/views/public.js
  src/pages/views/reply.js
  src/pages/views/search.js
  src/ssb.js
  src/views/index.js
  src/views/post.js
  src/views/template.js
Labels: help wanted, topic:enhancement

#51 fix docker file now that server.js is gone
  contrib/Dockerfile
Labels: topic:bug

#52 Add follow and unfollow
  CHANGELOG.md
  src/index.js
  src/models/index.js
  src/views/index.js
Labels: topic:enhancement

#62 Add note about supported Node.js versions
  README.md
Labels: topic:documentation

#65 Experiment with common-good module
  .eslintrc.js
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .stylelintrc
  .travis.yml
  README.md
  contrib/install-systemd-service.js
  docs/code-of-conduct.md
  docs/contributing.md
  docs/install.md
  package-lock.json
  package.json
  src/assets/style.css
  src/cli.js
  src/http.js
  src/index.js
  src/models/index.js
  src/models/markdown.js
  src/ssb.js
  src/views/index.js
  src/views/post.js
  src/views/template.js
Labels: topic:enhancement

#70 Add prototype for names in peer list
  src/index.js
  src/views/index.js
Labels: topic:enhancement

#72 Make Travis faster by removing double-build
  .travis.yml
  package.json
Labels: topic:enhancement

#76 Update npm dependencies for new common-good
  package-lock.json
  package.json
  src/index.js
  src/views/template.js
Labels: topic:bug

#75 Fix private reply with `recps` bug
  src/models/index.js
Labels: topic:bug

#81 Update Common-Good to stop using npm alias
  package-lock.json
  package.json
Labels: topic:bug

#79 Use ssb-backlinks to improve /inbox page load
  src/models/index.js
Labels: topic:enhancement

#82 Add some basic type info with JSDoc
  package-lock.json
  src/http.js
  src/models/index.js
  src/models/markdown.js
Labels: topic:enhancement

#83 Fix tangle bug when Patchwork is used as a server
  package-lock.json
  package.json
  src/ssb.js
Labels: topic:bug

#74 Change favicon dimensions to fit in tab
  src/assets/favicon.svg
Labels: topic:bug

#99 Use capitalization for Oasis links and buttons
  src/assets/style.css
  src/index.js
  src/models/index.js
  src/views/index.js
  src/views/post.js
  src/views/template.js
Labels: topic:enhancement

#95 Add simple nav sidebar on large screens
  src/assets/style.css
Labels: topic:enhancement

#92 Add buttons to 'meta' page to manage networking
  README.md
  package-lock.json
  package.json
  src/assets/style.css
  src/cli.js
  src/index.js
  src/models/index.js
  src/ssb.js
  src/views/index.js
Labels: topic:enhancement

#114 Hide private messages from author profiles
  package-lock.json
  src/index.js
  src/models/index.js
Labels: enhancement

#120 Replace "must" with "shall" in contributing.md
  docs/contributing.md
Labels: bug

#124 Specify exact Node.js engine support and test it
  .travis.yml
  package.json
Labels: enhancement

#125 Update Flotilla to drop SSB-Links2
  package-lock.json
  package.json
Labels: enhancement

#123 Add basic following page
  src/index.js
  src/models/index.js
  src/views/template.js
Labels: enhancement
