Repository fraction/oasis, pull requests merged in 2020-04, with the labels that each got.

#383 Fix footer button hover background
  src/assets/style.css
Labels: bug

#350 Add .mailmap for canonical identities
  .mailmap
Labels: bug, process

#352 Fall back to TCP socket if Unix connection fails
  src/ssb.js
Labels: bug

#388 Fix config bug
  src/ssb.js
Labels: bug

#389 Add very basic test suite
  .prettierignore
  package-lock.json
  package.json
  src/http.js
  src/index.js
  src/ssb.js
  test/basic.js
  test/lifecycle.js
Labels: bug, enhancement

#387 Update npm dependencies
  package-lock.json
  package.json
Labels: dependencies

#393 Fix private posts rendered alongside public posts
  src/models.js
Labels: bug

#398 Add --allow-host CLI flag for for proxy use-case
  src/cli.js
  src/http.js
  src/index.js
Labels: enhancement

#404 Fix "tpo" typo
  docs/contributing.md
Labels: documentation

#402 Replace setImmediate() with .on('listening')
  src/http.js
Labels: bug

#395 Start SSB service immediately instead of waiting
  src/ssb.js
Labels: bug

#405 Add Français (FR) to the language drop-down
  src/views/index.js
Labels: enhancement

#403 Introduces sync endpoint
  src/index.js
  src/models.js
  src/views/i18n.js
  src/views/index.js
Labels: enhancement

#409 Add timeout to sync and refactor
  src/models.js
Labels: enhancement

#408 Fix allow-host preset not working correctly
  src/cli.js
Labels: bug

#411 Replace "metric CSS" with --size-N
  src/assets/style.css
Labels: code style

#410 Fix summary style
  src/assets/style.css
Labels: cosmetic
